# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: sops

before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0
  - PKG=github.com/getsops/sops/v3/version

report_sizes: true

builds:
  - id: binary-linux
    main: ./cmd/sops
    binary: "{{ .ProjectName }}"
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - >
        -s -w
        -X "{{ .Env.PKG }}.Version={{ .Version }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: binary-darwin
    main: ./cmd/sops
    binary: "{{ .ProjectName }}"
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - >
        -s -w
        -X {{ .Env.PKG }}.Version={{ .Version }}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: binary-windows
    main: ./cmd/sops
    binary: "{{ .ProjectName }}"
    flags:
      - -trimpath
      - -buildmode=pie
      - -mod=readonly
    ldflags:
      - >
        -s -w
        -X {{ .Env.PKG }}.Version={{ .Version }}
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

universal_binaries:
  - id: binary-darwin-universal
    ids:
      - binary-darwin
    name_template: '{{ .ProjectName }}'
    replace: false
    mod_timestamp: "{{ .CommitTimestamp }}"

nfpms:
  - id: deb
    package_name: '{{ .ProjectName }}'
    file_name_template: '{{ .ConventionalFileName }}'
    vendor: custom-sops
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
    maintainer: custom-sops <custom@example.com>
    description: Simple and flexible tool for managing secrets
    license: MPL-2.0
    formats:
      - deb
      - rpm

snapshot:
  name_template: "{{ incpatch .Version }}-dev-{{ .ShortCommit }}"

archives:
  - id: archive-unix
    format: binary
    builds:
      - binary-linux
      - binary-darwin
    name_template: '{{ .ProjectName }}-v{{ .Version }}.{{ .Os }}.{{ .Arch }}'

  - id: archive-windows
    format: binary
    builds:
      - binary-windows
    name_template: '{{ .ProjectName }}-v{{ .Version }}.{{ .Arch }}'

  - id: archive-darwin-universal
    format: binary
    builds:
      - binary-darwin-universal
    name_template: '{{ .ProjectName }}-v{{ .Version }}.darwin'

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}.checksums.txt"
  algorithm: sha256
  ids:
    - archive-unix
    - archive-windows
    - archive-darwin-universal

changelog:
  use: github-native

release:
  prerelease: auto
  draft: false # 自动发布，而不是存为草稿
  header: |
    ## Installation

    To install `{{ .ProjectName }}`, download one of the pre-built binaries provided for your platform from the artifacts attached to this release.

    For instance, if you are using Linux on an AMD64 architecture:

    ```shell
    # Download the binary
    curl -LO https://github.com/{{ .Env.GITHUB_REPOSITORY }}/releases/download/{{ .Tag }}/{{ .ProjectName }}-v{{ .Version }}.linux.amd64

    # Move the binary in to your PATH
    mv {{ .ProjectName }}-v{{ .Version }}.linux.amd64 /usr/local/bin/{{ .ProjectName }}

    # Make the binary executable
    chmod +x /usr/local/bin/{{ .ProjectName }}
    ```

brews:
  - name: sops
    repository:
      owner: peiliqiancdt
      name: sops
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/peiliqiancdt/sops"
    description: "Editor of encrypted files"
    license: "MPL-2.0"
    ids:
      - archive-unix
    install: |
      bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
    test: |
      system "#{bin}/sops", "--version"
