# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sops < Formula
  desc "Editor of encrypted files"
  homepage "https://github.com/peiliqiancdt/sops"
  version "3.12.1-acs-1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peiliqiancdt/sops/releases/download/v3.12.1-acs-1/sops-v3.12.1-acs-1.darwin.amd64"
      sha256 "5d71a2b68b420646546392e883de6ce23ee60a325fd5becd753f81a54e7a9f07"

      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peiliqiancdt/sops/releases/download/v3.12.1-acs-1/sops-v3.12.1-acs-1.darwin.arm64"
      sha256 "041cb88cc90aeb6433ca167226b30af73b4b8d73a86dde9c27fa44852aab118e"

      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiliqiancdt/sops/releases/download/v3.12.1-acs-1/sops-v3.12.1-acs-1.linux.amd64"
      sha256 "1f6ee37156da1a1e6ad84689e1895641e0abff80b0c9c646d6c0a73bad5492c4"
      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiliqiancdt/sops/releases/download/v3.12.1-acs-1/sops-v3.12.1-acs-1.linux.arm64"
      sha256 "013d6a31c00355a9752e67d3e1511d24146a8e646d0c4df4811ae5e0d1e3638d"
      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
  end

  test do
    system "#{bin}/sops", "--version"
  end
end
