# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sops < Formula
  desc "Editor of encrypted files"
  homepage "https://github.com/peiliqiancdt/sops"
  version "3.12.1-acs-0.10"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peiliqiancdt/sops/releases/download/v3.12.1-acs-0.10/sops-v3.12.1-acs-0.10.darwin.amd64"
      sha256 "532f6ea17e7a7bba9b6d7daeea77191ef02c4276befeaefa93492067b397281c"

      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peiliqiancdt/sops/releases/download/v3.12.1-acs-0.10/sops-v3.12.1-acs-0.10.darwin.arm64"
      sha256 "f6353471f28a4664b0b71dd08d8c3dedb3f78624bdd692a716ac74ed90ee539e"

      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiliqiancdt/sops/releases/download/v3.12.1-acs-0.10/sops-v3.12.1-acs-0.10.linux.amd64"
      sha256 "6f586bc6ff82813bbb43391ff49ef5255bd4f62ae6165782430862880516b06b"
      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiliqiancdt/sops/releases/download/v3.12.1-acs-0.10/sops-v3.12.1-acs-0.10.linux.arm64"
      sha256 "2adbb84a230773f7a4dd5f159252bb0258ef4c632f2c2534fed5655a3fb2466e"
      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
  end

  test do
    system "#{bin}/sops", "--version"
  end
end
