# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sops < Formula
  desc "Editor of encrypted files"
  homepage "https://github.com/peiliqiancdt/sops"
  version "0.11-acs"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peiliqiancdt/sops/releases/download/v0.11-acs/sops-v0.11-acs.darwin.amd64"
      sha256 "1641140673d7a40eed7805897a0eba537c32d5e579054d221c72743732c54a4a"

      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/peiliqiancdt/sops/releases/download/v0.11-acs/sops-v0.11-acs.darwin.arm64"
      sha256 "c9778b07aac05fc5b0cb981647fb7b22ec54a9cf5f92dcf4937a8b38126c68f5"

      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiliqiancdt/sops/releases/download/v0.11-acs/sops-v0.11-acs.linux.amd64"
      sha256 "310cc8de7ca47bb47d646b9b9868e0a03c32e37876ddd2d3b714709cd6bf2486"
      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peiliqiancdt/sops/releases/download/v0.11-acs/sops-v0.11-acs.linux.arm64"
      sha256 "0ec288750386d09907574d5249f685d1047ad28a2838d1ee4a171c7de9d652d1"
      define_method(:install) do
        bin.install "sops-v#{version}.#{OS.kernel_name.downcase}.#{Hardware::CPU.arch}" => "sops"
      end
    end
  end

  test do
    system "#{bin}/sops", "--version"
  end
end
